import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Push Events
self.addEventListener('push', (event: any) => {
  let payload: any = {
    title: 'Sistema POS',
    message: 'Nuevos datos disponibles'
  };

  if (event.data) {
    try {
      payload = event.data.json();
    } catch (err) {
      payload = {
        title: 'Sistema POS',
        message: event.data.text()
      };
    }
  }

  const isDynamicTag = !payload.tag;
  const tag = payload.tag || `pos-notif-${Date.now()}`;

  const options = {
    body: payload.message || '',
    icon: '/logo_final.jpg',
    badge: '/logo_final.jpg',
    vibrate: [200, 100, 200, 100, 200],
    sound: '/whatsapp.wav',
    data: {
      url: payload.url || '/'
    },
    actions: [
      { action: 'open', title: 'Ver en Sistema POS' }
    ],
    tag: tag,
    renotify: isDynamicTag ? false : true,
    requireInteraction: true,
    silent: false
  };

  const clientsPromise = self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients: any[]) => {
    clients.forEach((client) => {
      client.postMessage({
        type: 'PUSH_NOTIFICATION_RECEIVED',
        title: payload.title,
        message: payload.message
      });
    });
  });

  event.waitUntil(
    Promise.all([
      self.registration.showNotification(payload.title || 'Sistema POS', options),
      clientsPromise
    ])
  );
});

// Handle Notification Click Event
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any[]) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin)) {
          if ('focus' in client) {
            client.focus();
          }
          if ('navigate' in client) {
            client.navigate(targetUrl);
          }
          return;
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
